# Generated by Django 4.0.4 on 2022-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.JSONField(default={'status': {'followers': [], 'following': []}}),
        ),
    ]
