# Generated by Django 4.0.4 on 2022-05-31 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_person_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pic',
        ),
    ]
