# Generated by Django 4.0.4 on 2022-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_person_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pic',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
